dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://192.168.102.130:2181
    timeout: 10000

  protocol:
    name: dubbo
    port: 20881

# 加载其他的application-*.yml文件，多个名称之前使用逗号分隔
spring:
  profiles:
    active: mybatis